# Используем официальный образ Node.js
FROM node:14

# Установка рабочей директории внутри контейнера
WORKDIR /usr/src/app

# Копирование зависимостей приложения (package.json и package-lock.json)
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование остальных файлов приложения
COPY . .

# Определение переменных среды
ENV PORT=5000
ENV MONGODB_URI="mongodb+srv://admin:admin12345@cluster0.xn2zx35.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
ENV GEMINI_API_KEY="AIzaSyDNbl76RxVRzAYREolFyde7l7EwAlREKQI"

# Открытие порта, который будет использоваться вашим приложением
EXPOSE 5000

# Запуск приложения при старте контейнера
CMD ["npm", "start"]
